### PR TITLE
Fix provenance fields.

### PR DESCRIPTION
**Pull request by msuozzo**

### CODE REVIEW

**Comment by TomHennen** [comment]
Can you also update the example provenance (or maybe it's easier if you update it once this is 'acceptable'?)?

**Comment by msuozzo** [comment]
Yep my plan was to do so once it's looked at / approved on the issue.

**Comment by MarkLodato** [comment]
LGTM. Let's update the example too, as suggested by Tom.

**Review by MarkLodato — APPROVED** [review]

**Comment by loosebazooka** [comment]
> Can you also update the example provenance (or maybe it's easier if you update it once this is 'acceptable'?)?

Example is generated by the example in the project.

**Pull request merged**
